const translationKeys = {
  en: {
    dashboard: "Dashboard",
    loans: "Loans",
    expenses: "Expenses",
    simulator: "Simulator",
    forecast: "Forecast",
    analytics: "Analytics",
    aiCoach: "AI Coach",
    payments: "Payments",
    admin: "Admin",
    logout: "Logout",
    welcome: "Welcome back",
    recoveryScore: "Recovery Score",
    totalDebt: "Total Debt",
    income: "Monthly Income",
    outflow: "Monthly Expenses",
    surplus: "Monthly Surplus",
    activeLoans: "Active Loans",
    riskLevel: "Risk Level",
    recoveryStatus: "Recovery Status",
    strengths: "Strengths",
    weaknesses: "Weaknesses",
    suggestions: "Suggestions",
    simulate: "Simulate",
    proposedEmi: "Proposed EMI",
    currentEmi: "Current EMI",
    tenure: "Tenure",
    months: "months",
    interestSaved: "Interest Saved",
    monthsReduced: "Months Reduced",
    debtFreeDate: "Debt-Free Date",
    savings: "Savings",
    remainingInterest: "Remaining Interest",
    recommendedPayment: "Recommended Payment",
    payoffTimeline: "Payoff Timeline",
    paymentTracker: "Payment Tracker",
    compliance: "Compliance",
    adminDashboard: "Admin Console",
    totalUsers: "Total Users",
    avgScore: "Average Score",
    commonDebtType: "Common Debt Type",
    debtManaged: "Total Debt Managed",
    languages: "Preferred Languages",
    searchPlaceholder: "Search loans...",
    addLoan: "Add Loan",
    editLoan: "Edit Loan",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    askCoach: "Ask our AI Coach...",
    audit: "Financial Audit",
    financialProfile: "Financial Profile"
  },
  te: {
    dashboard: "డాష్‌బోర్డ్",
    loans: "రుణాలు",
    expenses: "ఖర్చులు",
    simulator: "సిమ్యులేటర్",
    forecast: "అంచనా",
    analytics: "విశ్లేషణలు",
    aiCoach: "AI కోచ్",
    payments: "చెల్లింపులు",
    admin: "అడ్మిన్",
    logout: "లాగ్అవుట్",
    welcome: "తిరిగి స్వాగతం",
    recoveryScore: "రికవరీ స్కోర్",
    totalDebt: "మొత్తం అప్పు",
    income: "నెలవారీ ఆదాయం",
    outflow: "నెలవారీ ఖర్చులు",
    surplus: "నెలవారీ మిగులు",
    activeLoans: "యాక్టివ్ రుణాలు",
    riskLevel: "రిస్క్ స్థాయి",
    recoveryStatus: "రికవరీ స్థితి",
    strengths: "బలాలు",
    weaknesses: "బలహీనతలు",
    suggestions: "సూచనలు",
    simulate: "సిమ్యులేట్",
    proposedEmi: "ప్రతిపాదిత ఈఎంఐ",
    currentEmi: "ప్రస్తుత ఈఎంఐ",
    tenure: "వ్యవధి",
    months: "నెలలు",
    interestSaved: "ఆదా అయిన వడ్డీ",
    monthsReduced: "తగ్గిన నెలలు",
    debtFreeDate: "రుణ విముక్తి తేదీ",
    savings: "పొదుపు",
    remainingInterest: "మిగిలిన వడ్డీ",
    recommendedPayment: "సిఫార్సు చేసిన చెల్లింపు",
    payoffTimeline: "చెల్లింపు కాలక్రమం",
    paymentTracker: "చెల్లింపుల ట్రాకర్",
    compliance: "చెల్లింపుల కట్టుబాటు",
    adminDashboard: "అడ్మిన్ కన్సోల్",
    totalUsers: "మొత్తం వినియోగదారులు",
    avgScore: "సగటు స్కోరు",
    commonDebtType: "సాధారణ రుణ రకం",
    debtManaged: "మొత్తం నిర్వహించబడుతున్న అప్పు",
    languages: "ప్రాధాన్యత భాషలు",
    searchPlaceholder: "రుణాల కోసం వెతకండి...",
    addLoan: "రుణాన్ని జోడించు",
    editLoan: "రుణాన్ని సవరించు",
    delete: "తొలగించు",
    save: "సేవ్",
    cancel: "రద్దు",
    askCoach: "మా AI కోచ్‌ను అడగండి...",
    audit: "ఆర్థిక ఆడిట్",
    financialProfile: "ఆర్థిక ప్రొఫైల్"
  },
  hi: {
    dashboard: "डैशबोर्ड",
    loans: "ऋण",
    expenses: "खर्च",
    simulator: "सिम्युलेटर",
    forecast: "पूर्वानुमान",
    analytics: "विश्लेषण",
    aiCoach: "AI कोच",
    payments: "भुगतान",
    admin: "एडमिन",
    logout: "लॉगआउट",
    welcome: "आपका स्वागत है",
    recoveryScore: "सुधार स्कोर",
    totalDebt: "कुल ऋण",
    income: "मासिक आय",
    outflow: "मासिक खर्च",
    surplus: "मासिक अधिशेष",
    activeLoans: "सक्रिय ऋण",
    riskLevel: "जोखिम स्तर",
    recoveryStatus: "सुधार की स्थिति",
    strengths: "मजबूती",
    weaknesses: "कमियां",
    suggestions: "सुझाव",
    simulate: "सिम्युलेट",
    proposedEmi: "प्रस्तावित ईएमआई",
    currentEmi: "वर्तमान ईएमआई",
    tenure: "अवधि",
    months: "महीने",
    interestSaved: "बचाया गया ब्याज",
    monthsReduced: "कम हुए महीने",
    debtFreeDate: "ऋण-मुक्त तिथि",
    savings: "बचत",
    remainingInterest: "शेष ब्याज",
    recommendedPayment: "अनुशंसित भुगतान",
    payoffTimeline: "भुगतान समय-सीमा",
    paymentTracker: "भुगतान ट्रैकर",
    compliance: "भुगतान अनुपालन",
    adminDashboard: "एडमिन कंसोल",
    totalUsers: "कुल उपयोगकर्ता",
    avgScore: "औसत स्कोर",
    commonDebtType: "सामान्य ऋण प्रकार",
    debtManaged: "कुल प्रबंधित ऋण",
    languages: "पसंदीदा भाषाएं",
    searchPlaceholder: "ऋण खोजें...",
    addLoan: "ऋण जोड़ें",
    editLoan: "ऋण संपादित करें",
    delete: "हटाएं",
    save: "सहेजें",
    cancel: "रद्द करें",
    askCoach: "हमारे AI कोच से पूछें...",
    audit: "वित्तीय ऑडिट",
    financialProfile: "वित्तीय प्रोफ़ाइल"
  },
  ta: {
    dashboard: "டாஷ்போர்டு",
    loans: "கடன்கள்",
    expenses: "செலவுகள்",
    simulator: "சிமுலேட்டர்",
    forecast: "கணிப்பு",
    analytics: "பகுப்பாய்வு",
    aiCoach: "AI கோச்",
    payments: "செலுத்தல்கள்",
    admin: "அட்மின்",
    logout: "வெளியேறு",
    welcome: "மீண்டும் வருக",
    recoveryScore: "மீட்சி மதிப்பெண்",
    totalDebt: "மொத்த கடன்",
    income: "மாத வருமானம்",
    outflow: "மாத செலவுகள்",
    surplus: "மாத உபரி",
    activeLoans: "செயலில் உள்ள கடன்கள்",
    riskLevel: "ஆபத்து நிலை",
    recoveryStatus: "மீட்சி நிலை",
    strengths: "பலங்கள்",
    weaknesses: "பலவீனங்கள்",
    suggestions: "பரிந்துரைகள்",
    simulate: "சிமுலேட்",
    proposedEmi: "பரிந்துரை தவணை",
    currentEmi: "தற்போதைய தவணை",
    tenure: "கால அளவு",
    months: "மாதங்கள்",
    interestSaved: "சேமிக்கப்பட்ட வட்டி",
    monthsReduced: "குறைக்கப்பட்ட மாதங்கள்",
    debtFreeDate: "கடன் இல்லாத தேதி",
    savings: "சேமிப்பு",
    remainingInterest: "மீதமுள்ள வட்டி",
    recommendedPayment: "பரிந்துரைக்கப்பட்ட தொகை",
    payoffTimeline: "கடன் அடைப்பு காலவரிசை",
    paymentTracker: "செலுத்தல் கண்காணிப்பான்",
    compliance: "செலுத்தல் ஒழுங்கு",
    adminDashboard: "அட்மின் கன்சோல்",
    totalUsers: "மொத்த பயனர்கள்",
    avgScore: "சராசரி மதிப்பெண்",
    commonDebtType: "பொதுவான கடன் வகை",
    debtManaged: "நிர்வகிக்கப்படும் மொத்த கடன்",
    languages: "விருப்பமான மொழிகள்",
    searchPlaceholder: "கடன்களைத் தேடுங்கள்...",
    addLoan: "கடனைச் சேர்",
    editLoan: "கடனைத் திருத்து",
    delete: "நீக்கு",
    save: "சேமி",
    cancel: "ரத்து செய்",
    askCoach: "எங்கள் AI கோச்சிடம் கேளுங்கள்...",
    audit: "நிதி தணிக்கை",
    financialProfile: "நிதி சுயவிவரம்"
  }
};

export const getTranslation = (lang, key) => {
  const language = translationKeys[lang] ? lang : 'en';
  return translationKeys[language][key] || translationKeys['en'][key] || key;
};

export default translationKeys;
